name: Lets Start Filters
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "https://github.com/TroJanzHEX/Unlimited-Filter-Bot"
          replace: "https://github.com/Mr-Dark-Prince/Unlimited-Filter-Bot"
      - name: Pull All Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'ğŸ“ºà´¸à´¿àµ½à´®à´¾ à´•à´¾à´Ÿàµà´Ÿ à´®à´¾à´® ğŸ˜ğŸ˜‚'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: Mr-Dark-Prince
          commit_user_email: 73339924+Mr-Dark-Prince@users.noreply.github.com
          commit_author: Mr-Dark-Prince <73339924+Mr-Dark-Prince@users.noreply.github.com>
